"""Production capacity — the deterministic calculation (FR-6, ADR-3).

This is the function acceptance criterion 4 is about: *"production quantities
are generated by deterministic calculation functions rather than invented by
the LLM."* It is pure — typed inputs in, a typed breakdown out, no database, no
model, no clock — so a test can pin an exact integer against a fixed dataset.

The algorithm is the one specified in `docs/02-architecture.md` §5:

    effective_h(m)    = max(0, planned_h(m) - maintenance_h(m))
    machine_capacity  = Σ over eligible machines: floor(effective_h × 60 / cycle_time_min)
    material_capacity = floor(available_quantity / material_qty_per_unit)
    final_capacity    = min(machine_capacity, material_capacity)

Two details are deliberate.

**Decimal, not float.** `db/verify.sql` computes the same numbers in SQL over
`NUMERIC` columns, and the two must agree exactly — a float that lands on
856.9999999 instead of 857 would break that agreement at a boundary. The engine
therefore does its arithmetic in `Decimal` and floors explicitly.

**Per-machine flooring.** The floor is applied to each machine and then summed,
not applied once to the total: a machine cannot produce a fraction of a part, so
three machines with 5 minutes of slack each waste that slack individually. This
matches the SQL oracle, and it is the physically honest reading.
"""

from __future__ import annotations

from decimal import ROUND_FLOOR, Decimal

from pydantic import BaseModel, Field

from app.schemas.mes import InventoryItem, MachineAvailability, Part
from app.timewindow import ResolvedWindow

MINUTES_PER_HOUR = Decimal(60)


class CapacityUnavailable(Exception):
    """A precondition failed, so there is no number to give.

    Carries the field that is missing so the refusal can name it, exactly as the
    tool layer does — the agent never has to guess why it cannot answer.
    """

    def __init__(self, reason: str, *, entity: str, field: str | None = None) -> None:
        super().__init__(reason)
        self.reason = reason
        self.entity = entity
        self.field = field


class MachineCapacityLine(BaseModel):
    """What one machine contributes, with the arithmetic visible."""

    machine_id: str
    status: str
    eligible: bool
    ineligible_reason: str | None = None
    planned_hours: float
    maintenance_hours: float
    effective_hours: float
    parts_possible: int = Field(description="floor(effective_hours × 60 / cycle_time_min)")


class CapacityResult(BaseModel):
    part_id: str
    window: ResolvedWindow | None = None
    cycle_time_min: float
    required_machine_type: str

    machines: list[MachineCapacityLine] = Field(default_factory=list)
    eligible_machine_ids: list[str] = Field(default_factory=list)
    total_effective_hours: float = 0.0

    machine_capacity: int
    material_id: str | None = None
    material_qty_per_unit: float | None = None
    available_quantity: float | None = None
    material_capacity: int | None = None

    final_capacity: int
    binding_constraint: str = Field(description="'machine' or 'material'")
    formula: list[str] = Field(
        default_factory=list,
        description="The arithmetic, line by line, so the answer can show its working",
    )


def _floor(value: Decimal) -> int:
    return int(value.to_integral_value(rounding=ROUND_FLOOR))


def _dec(value: float | int | Decimal) -> Decimal:
    return Decimal(str(value))


def calculate_capacity(
    *,
    part: Part,
    availability: list[MachineAvailability],
    inventory: InventoryItem | None,
    window: ResolvedWindow | None = None,
) -> CapacityResult:
    """Maximum feasible quantity of `part` over the window.

    Raises `CapacityUnavailable` rather than returning a number when a
    precondition fails. There is no "best effort" answer here: a capacity figure
    the factory manager cannot rely on is worse than no figure.
    """
    if part.cycle_time_min is None:
        raise CapacityUnavailable(
            f"Cycle time is not recorded for {part.part_id}, so its production capacity "
            "cannot be calculated.",
            entity=part.part_id,
            field="parts.cycle_time_min",
        )
    if part.cycle_time_min <= 0:
        raise CapacityUnavailable(
            f"Cycle time for {part.part_id} is not a positive number.",
            entity=part.part_id,
            field="parts.cycle_time_min",
        )

    cycle = _dec(part.cycle_time_min)
    eligible = [m for m in availability if m.eligible]

    if not eligible:
        raise CapacityUnavailable(
            f"No machine of type {part.required_machine_type} is available to run "
            f"{part.part_id} in this period.",
            entity=part.part_id,
        )

    lines: list[MachineCapacityLine] = []
    machine_capacity = 0
    for machine in availability:
        parts_possible = 0
        if machine.eligible:
            minutes = _dec(machine.effective_hours) * MINUTES_PER_HOUR
            parts_possible = _floor(minutes / cycle)
            machine_capacity += parts_possible
        lines.append(
            MachineCapacityLine(
                machine_id=machine.machine_id,
                status=machine.status,
                eligible=machine.eligible,
                ineligible_reason=machine.ineligible_reason,
                planned_hours=machine.planned_hours,
                maintenance_hours=machine.maintenance_hours,
                effective_hours=machine.effective_hours,
                parts_possible=parts_possible,
            )
        )

    material_capacity: int | None = None
    if part.material_qty_per_unit is None:
        raise CapacityUnavailable(
            f"Material consumption per unit is not recorded for {part.part_id}, so the "
            "material limit cannot be checked.",
            entity=part.part_id,
            field="parts.material_qty_per_unit",
        )
    if inventory is None:
        raise CapacityUnavailable(
            f"No stock record exists for {part.material_id}, the material {part.part_id} consumes.",
            entity=part.material_id or part.part_id,
            field="inventory.available_quantity",
        )
    if inventory.available_quantity is None:
        raise CapacityUnavailable(
            f"Stock for {inventory.material_id} has not been counted, so the material "
            "limit is unknown.",
            entity=inventory.material_id,
            field="inventory.available_quantity",
        )

    material_capacity = _floor(
        _dec(inventory.available_quantity) / _dec(part.material_qty_per_unit)
    )

    final_capacity = min(machine_capacity, material_capacity)
    binding = "material" if material_capacity < machine_capacity else "machine"

    total_effective = sum(_dec(m.effective_hours) for m in eligible)
    formula = [
        f"cycle time {part.cycle_time_min:g} min/part",
        *[
            f"{line.machine_id}: {line.planned_hours:g} planned − "
            f"{line.maintenance_hours:g} maintenance = {line.effective_hours:g} h "
            f"→ floor({line.effective_hours:g} × 60 ÷ {part.cycle_time_min:g}) = "
            f"{line.parts_possible} parts"
            for line in lines
            if line.eligible
        ],
        f"machine capacity = {' + '.join(str(x.parts_possible) for x in lines if x.eligible)}"
        f" = {machine_capacity} parts",
        f"material capacity = floor({inventory.available_quantity:g} ÷ "
        f"{part.material_qty_per_unit:g}) = {material_capacity} parts",
        f"final = min({machine_capacity}, {material_capacity}) = {final_capacity} parts "
        f"({binding}-constrained)",
    ]

    return CapacityResult(
        part_id=part.part_id,
        window=window,
        cycle_time_min=part.cycle_time_min,
        required_machine_type=part.required_machine_type,
        machines=lines,
        eligible_machine_ids=[m.machine_id for m in eligible],
        total_effective_hours=float(total_effective),
        machine_capacity=machine_capacity,
        material_id=inventory.material_id,
        material_qty_per_unit=part.material_qty_per_unit,
        available_quantity=inventory.available_quantity,
        material_capacity=material_capacity,
        final_capacity=final_capacity,
        binding_constraint=binding,
        formula=formula,
    )
